STATE_SIZE = 47

# Observation Space [0,1]
# Input Payload
# Payload Appearance
CONTAIN_SCRIPT_STRING = 0
ALERT_STRING = 1
PARENTHESIS = 2
STRING_PREFIX = 3
EVENT_ELEMENT = 4
ATTRIBUTE_ELEMENT = 5
JS_PAYLOAD = 6
HTML_COMMENT_USED = 7
JS_COMMENT_USED = 8
URL_PAYLOAD = 9
JAVASCRIPT_FILE_NAME = 10
HTML_TAG_USED = 11
HTML_SCRIPT_TAG_USED = 12
HTML_MEDIA_TAG_USED = 13
SINGLE_QUOTATION = 14
DOUBLE_QUOTATION = 15
BACK_TICK = 16
BACKSLASH = 17
BRACKET = 18
PREFIX_ENTER = 19
INSERT_EFFECTIVE_TAG = 20

JAVASCRIPT_CODE = 21
URL_ENCODING = 22
HEXA_ENCODING = 23
CODE_OBSFUSCATION = 24
CHARACTER_UPPER = 25
ATTRIBUTE_UPPER = 26
TAG_INSERTED = 27
NO_WHITE_SPACE = 28

# Payload Repititiveness
INPUT_CORPUS = 29
PREVIOUS_ACTION = 30  
CURRENT_ACTION = 31

# Response
# Reflected Payload Appearance
TAG_INJECTED = 32
STRING_INJECTED = 33
SIMILARITY = 34

# PayLoad Context information
CONTENT_TYPE = 35
DEFAULT_PAYLOAD_TYPE = 36
INJECTION_POINT_TYPE = 37
BEFORE_INJECTION_POINT = 38
BEHIND_INJECTION_POINT = 39
ESCAPE_STRING = 40
EFFECTIVE_TAG_TYPE = 41
FIRST_MAGIC_STRING = 42
SECOND_MAGIC_STRING = 43
THIRD_MAGIC_STRING = 44
FOURTH_MAGIC_STRING = 45

# Attack 
# Attack Result
ATTACK_SUCCESS = 46















#BASE64 = 20






# [Output Part]

# [Action Selection]


# [Injection Point Informain]


#DEFAULT_PAYLOAD_TYPE = 41
# [Action Count]
"""
USING_SCRIPT_TAG = 18 # 0
PATTERN2_PAYLOAD = 19 # 1
MUTATE_PREFIX_SLASHBRACKET = 20 # 2

MUTATE_HTML_TAG = 21 # 3
MUTATE_PREFIX_DOUBLE_QUOTE = 22 #4
MUTATE_PREFIX_SINGLE_QUOTE = 23 # 5
MUTATE_PREFIX = 24 # 6
MUTATE_SUFFIX = 25 #7
TAG_LOWER_TO_UPPER = 26 # 8
INSERT_TAG_INTO_TAG = 27 # 9
INSERT_EFFECTIVE_TAG = 28 # 10
MUTATE_PREFIX_COMMENT = 29 # 11
MUTATE_PREFIX_STYLE = 30 # 12
JAVASCRIPT_VALUE = 31 # 13
URL_VALUE = 32 # 14
JAVASCRIPT_FILE = 33  # 15
IN_JAVASCRIPT = 34 # 16
"""



